/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author anhng
 */
public class trangchufram extends javax.swing.JFrame {

    /**
     * Creates new form trangchufram
     * @param form
     */
    
    public void addFormToPnview(JFrame form) {
        pnview.removeAll(); 
        pnview.add(form.getContentPane()); 
        pnview.revalidate(); 
        pnview.repaint();
    }
    public trangchufram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBoderFrm1 = new PanelBoder.PanelBoderFrm();
        pnview = new PanelBoder.PanelBoderFrm();
        panelBoderFrm3 = new PanelBoder.PanelBoderFrm();
        panelBoderFrm4 = new PanelBoder.PanelBoderFrm();
        jLabel1 = new javax.swing.JLabel();
        jpnxlvp = new PanelBoder.PanelBoderFrm();
        labDangKiNoiTru = new javax.swing.JLabel();
        panelBoderFrm6 = new PanelBoder.PanelBoderFrm();
        labDSDangKi = new javax.swing.JLabel();
        panelBoderFrm7 = new PanelBoder.PanelBoderFrm();
        labDSHopDong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBoderFrm1.setBackground(new java.awt.Color(0, 51, 102));

        pnview.setBackground(new java.awt.Color(253, 240, 205));

        javax.swing.GroupLayout pnviewLayout = new javax.swing.GroupLayout(pnview);
        pnview.setLayout(pnviewLayout);
        pnviewLayout.setHorizontalGroup(
            pnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        pnviewLayout.setVerticalGroup(
            pnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        panelBoderFrm3.setBackground(new java.awt.Color(253, 240, 205));

        panelBoderFrm4.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trang chủ");

        javax.swing.GroupLayout panelBoderFrm4Layout = new javax.swing.GroupLayout(panelBoderFrm4);
        panelBoderFrm4.setLayout(panelBoderFrm4Layout);
        panelBoderFrm4Layout.setHorizontalGroup(
            panelBoderFrm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBoderFrm4Layout.setVerticalGroup(
            panelBoderFrm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnxlvp.setBackground(new java.awt.Color(0, 51, 102));
        jpnxlvp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnxlvpMouseClicked(evt);
            }
        });

        labDangKiNoiTru.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labDangKiNoiTru.setForeground(new java.awt.Color(255, 255, 255));
        labDangKiNoiTru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDangKiNoiTru.setText("Đăng kí nội trú");
        labDangKiNoiTru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labDangKiNoiTruMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnxlvpLayout = new javax.swing.GroupLayout(jpnxlvp);
        jpnxlvp.setLayout(jpnxlvpLayout);
        jpnxlvpLayout.setHorizontalGroup(
            jpnxlvpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnxlvpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labDangKiNoiTru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnxlvpLayout.setVerticalGroup(
            jpnxlvpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnxlvpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labDangKiNoiTru, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBoderFrm6.setBackground(new java.awt.Color(0, 51, 102));

        labDSDangKi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labDSDangKi.setForeground(new java.awt.Color(255, 255, 255));
        labDSDangKi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDSDangKi.setText("Danh sách đăng kí");
        labDSDangKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labDSDangKiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoderFrm6Layout = new javax.swing.GroupLayout(panelBoderFrm6);
        panelBoderFrm6.setLayout(panelBoderFrm6Layout);
        panelBoderFrm6Layout.setHorizontalGroup(
            panelBoderFrm6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoderFrm6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labDSDangKi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBoderFrm6Layout.setVerticalGroup(
            panelBoderFrm6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoderFrm6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labDSDangKi, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBoderFrm7.setBackground(new java.awt.Color(0, 51, 102));

        labDSHopDong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labDSHopDong.setForeground(new java.awt.Color(255, 255, 255));
        labDSHopDong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDSHopDong.setText("Danh sách hợp đồng");
        labDSHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labDSHopDongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBoderFrm7Layout = new javax.swing.GroupLayout(panelBoderFrm7);
        panelBoderFrm7.setLayout(panelBoderFrm7Layout);
        panelBoderFrm7Layout.setHorizontalGroup(
            panelBoderFrm7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm7Layout.createSequentialGroup()
                .addComponent(labDSHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBoderFrm7Layout.setVerticalGroup(
            panelBoderFrm7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoderFrm7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labDSHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBoderFrm3Layout = new javax.swing.GroupLayout(panelBoderFrm3);
        panelBoderFrm3.setLayout(panelBoderFrm3Layout);
        panelBoderFrm3Layout.setHorizontalGroup(
            panelBoderFrm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBoderFrm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelBoderFrm7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelBoderFrm4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnxlvp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBoderFrm6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelBoderFrm3Layout.setVerticalGroup(
            panelBoderFrm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoderFrm3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBoderFrm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnxlvp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBoderFrm6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBoderFrm7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );

        javax.swing.GroupLayout panelBoderFrm1Layout = new javax.swing.GroupLayout(panelBoderFrm1);
        panelBoderFrm1.setLayout(panelBoderFrm1Layout);
        panelBoderFrm1Layout.setHorizontalGroup(
            panelBoderFrm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoderFrm1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBoderFrm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBoderFrm1Layout.setVerticalGroup(
            panelBoderFrm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBoderFrm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBoderFrm3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBoderFrm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBoderFrm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpnxlvpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnxlvpMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jpnxlvpMouseClicked

    private void labDangKiNoiTruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labDangKiNoiTruMouseClicked
    FDKNoiTru fDKNoiTru = new FDKNoiTru();
    pnview.removeAll(); // Xóa tất cả các thành phần hiện có trong pnview
    pnview.add(fDKNoiTru.getContentPane()); // Thêm form vào pnview
    pnview.revalidate(); // Cập nhật giao diện
    pnview.repaint();
    }//GEN-LAST:event_labDangKiNoiTruMouseClicked

    private void labDSDangKiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labDSDangKiMouseClicked
        // TODO add your handling code here:
        FDSDangKi fDSDangKi = new FDSDangKi();
    pnview.removeAll(); // Xóa tất cả các thành phần hiện có trong pnview
    pnview.add(fDSDangKi.getContentPane()); // Thêm form vào pnview
    pnview.revalidate(); // Cập nhật giao diện
    pnview.repaint();
    }//GEN-LAST:event_labDSDangKiMouseClicked

    private void labDSHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labDSHopDongMouseClicked
        // TODO add your handling code here:
        FDSHopDong fDSHopDong = new FDSHopDong();
    pnview.removeAll(); // Xóa tất cả các thành phần hiện có trong pnview
    pnview.add(fDSHopDong.getContentPane()); // Thêm form vào pnview
    pnview.revalidate(); // Cập nhật giao diện
    pnview.repaint();
    }//GEN-LAST:event_labDSHopDongMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trangchufram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trangchufram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trangchufram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trangchufram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trangchufram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private PanelBoder.PanelBoderFrm jpnxlvp;
    private javax.swing.JLabel labDSDangKi;
    private javax.swing.JLabel labDSHopDong;
    private javax.swing.JLabel labDangKiNoiTru;
    private PanelBoder.PanelBoderFrm panelBoderFrm1;
    private PanelBoder.PanelBoderFrm panelBoderFrm3;
    private PanelBoder.PanelBoderFrm panelBoderFrm4;
    private PanelBoder.PanelBoderFrm panelBoderFrm6;
    private PanelBoder.PanelBoderFrm panelBoderFrm7;
    private PanelBoder.PanelBoderFrm pnview;
    // End of variables declaration//GEN-END:variables

    
}
