# Generated by Django 5.0.4 on 2024-12-16 14:46

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('MaDH', models.AutoField(primary_key=True, serialize=False)),
                ('TongTien', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('SoLuong', models.IntegerField(default=0)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('user_address', models.CharField(blank=True, default='', max_length=255)),
                ('user_phone', models.CharField(blank=True, default='', max_length=15)),
                ('MucGiamGia', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('TrangThai', models.CharField(choices=[('don_moi', 'Đơn mới'), ('cho_xac_nhan', 'Chờ xác nhận'), ('dang_xu_ly', 'Đang xử lý'), ('dang_giao', 'Đang giao'), ('da_hoan_thanh', 'Đã hoàn thành')], default='don_moi', max_length=20)),
                ('NgayDat', models.DateField(blank=True, null=True)),
                ('NgayDuKien', models.DateField(blank=True, null=True)),
                ('NgayNhan', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonViTinh',
            fields=[
                ('MaDVT', models.AutoField(primary_key=True, serialize=False)),
                ('dvt', models.CharField(max_length=255, unique=True)),
                ('IsDelete', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('MaKho', models.AutoField(primary_key=True, serialize=False)),
                ('TenKho', models.CharField(max_length=100)),
                ('DiaChi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Loai',
            fields=[
                ('MaLoai', models.AutoField(primary_key=True, serialize=False)),
                ('TenLoai', models.CharField(max_length=255)),
                ('IsDelete', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('MaNCC', models.AutoField(primary_key=True, serialize=False)),
                ('TenNCC', models.CharField(max_length=255)),
                ('DiaChi', models.CharField(max_length=255)),
                ('SoDienThoai', models.CharField(max_length=20)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Website', models.URLField(blank=True, null=True)),
                ('IsDelete', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quan',
            fields=[
                ('MaQuan', models.AutoField(primary_key=True, serialize=False)),
                ('TenQuan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThanhPho',
            fields=[
                ('MaTP', models.AutoField(primary_key=True, serialize=False)),
                ('TenTP', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('MaVoucher', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenVoucher', models.CharField(max_length=255)),
                ('MoTa', models.TextField()),
                ('NgayBatDau', models.DateField()),
                ('NgayKetThuc', models.DateField()),
                ('PhanTramGiam', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('HanMucApDung', models.PositiveIntegerField(default=0)),
                ('SoLuong', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('MaDG', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('NoiDung', models.TextField()),
                ('NgayViet', models.DateField()),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('MaDH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_danh_gia', to='Home.donhang')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('MaPhieuNhap', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('NgayNhap', models.DateField(auto_now_add=True)),
                ('TongSoLuong', models.IntegerField(default=0)),
                ('TongTienNhap', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('TrangThai', models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('GhiChu', models.TextField(blank=True, null=True)),
                ('IsDelete', models.DateTimeField(blank=True, null=True)),
                ('NhaCungCap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='Phuong',
            fields=[
                ('MaPhuong', models.AutoField(primary_key=True, serialize=False)),
                ('TenPhuong', models.CharField(max_length=255)),
                ('quan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phuong', to='Home.quan')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.AutoField(primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=255)),
                ('TrongLuong', models.CharField(max_length=255)),
                ('NguonGoc', models.CharField(max_length=255)),
                ('SoLuongHienTai', models.IntegerField(default=0)),
                ('GiaBan', models.DecimalField(decimal_places=3, max_digits=10)),
                ('BaoQuan', models.TextField()),
                ('HinhAnh', models.ImageField(upload_to='products/')),
                ('TinhTrang', models.BooleanField(default=False)),
                ('MoTa', models.TextField()),
                ('MucDoHu', models.BooleanField(default=False)),
                ('IsDelete', models.DateTimeField(blank=True, null=True)),
                ('DVT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanpham', to='Home.donvitinh')),
                ('MaLoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.loai')),
            ],
        ),
        migrations.CreateModel(
            name='CT_PhieuNhap',
            fields=[
                ('MaCTPN', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuongNhap', models.IntegerField()),
                ('GiaNhap', models.DecimalField(decimal_places=3, max_digits=10)),
                ('NgaySanXuat', models.DateField(blank=True, null=True)),
                ('NgayHetHan', models.DateField(blank=True, null=True)),
                ('ThanhTien', models.DecimalField(decimal_places=3, max_digits=12)),
                ('PhieuNhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_phieunhap', to='Home.phieunhap')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_phieunhap', to='Home.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='CT_DonHang',
            fields=[
                ('MaCTDH', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField(default=0)),
                ('ThanhTien', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_donhang', to='Home.donhang')),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='SanPhamHu',
            fields=[
                ('MaSP_Hu', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField()),
                ('NgayHu', models.DateField(blank=True, null=True)),
                ('LyDo', models.TextField()),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='static/damage/')),
                ('IsDelete', models.BooleanField(default=False)),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sanpham')),
            ],
        ),
        migrations.AddField(
            model_name='quan',
            name='thanh_pho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quan', to='Home.thanhpho'),
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuongTon', models.IntegerField()),
                ('NgayHetHan', models.DateField(blank=True, null=True)),
                ('NgayNhapKho', models.DateField(auto_now_add=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('Kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tonkho_set', to='Home.kho')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sanpham')),
            ],
        ),
        migrations.AddField(
            model_name='donhang',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.voucher'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=255)),
                ('ngaydangnhap', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Home.thanhpho')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Home.quan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Home.phuong')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('MaTin', models.AutoField(primary_key=True, serialize=False)),
                ('TieuDe', models.CharField(max_length=255)),
                ('NoiDung', ckeditor.fields.RichTextField()),
                ('AnhDaiDien', models.ImageField(blank=True, null=True, upload_to='news/thumbnails/')),
                ('Video', models.URLField(blank=True, null=True)),
                ('NgayDang', models.DateField(auto_now_add=True)),
                ('TacGia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donhang',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
