use master
drop database QL_KARA

CREATE DATABASE QL_KARA

GO
USE QL_KARA
GO

CREATE TABLE NHANVIEN
(
    MANV NCHAR(10) NOT NULL,
    TENNV NVARCHAR(50),
    SDT NVARCHAR(15),
    MAIL NVARCHAR(50),
    DIACHI NVARCHAR(50),
    CHUCVU NVARCHAR(30),
    GIOITINH NVARCHAR(10),
	TAIKHOAN CHAR (30),
	MATKHAU CHAR(30),
    CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
)
GO

CREATE TABLE KHACHHANG
(
    MAKH NCHAR(10) NOT NULL,
    TENKH NVARCHAR(50),
    SDT NVARCHAR(15),
    DIACHI NVARCHAR(50),
    GIAMGIA FLOAT,

    CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
)
GO

CREATE TABLE LOAIPHONG
(
    MALP NCHAR(10) NOT NULL,
    TENLP NVARCHAR(30),
    DONGIA INT,
    CONSTRAINT PK_LOAIPHONG PRIMARY KEY(MALP)
)
GO

CREATE TABLE PHONG
(
    MAPHONG NCHAR(10) NOT NULL,
    MALP NCHAR(10),
    TRANGTHAI NVARCHAR(30),
    NGUOITAO NVARCHAR(50),
    NGAYTAO DATETIME,

    CONSTRAINT PK_PHONG PRIMARY KEY(MAPHONG),
    CONSTRAINT FK_PHONG_LOAIPHONG FOREIGN KEY (MALP) REFERENCES LOAIPHONG(MALP)
)
GO

CREATE TABLE KHUYENMAI
(
    MAKM NCHAR(10) NOT NULL,
    TGBATDAU DATETIME,
    TGKETTHUC DATETIME,
    GIAMGIA INT,
    SOLUONG INT,
    CONSTRAINT PK_KHUYENMAI PRIMARY KEY(MAKM)
)
GO

CREATE TABLE MATHANG
(
    MAMH NCHAR(10) NOT NULL,
    TENMH NVARCHAR(30),
    LOAIMH NVARCHAR(30),
    NGUOITAO NVARCHAR(50),
    NGAYTAO DATETIME,
    CONSTRAINT PK_MATHANG PRIMARY KEY(MAMH)
)
GO

CREATE TABLE HOADONNHAP
(
    MAHD NCHAR(10) NOT NULL,
    NGUOITAO NVARCHAR(50),
    NGAYTAO DATETIME,
    CONSTRAINT PK_HOADONNHAP PRIMARY KEY(MAHD)
)
GO

CREATE TABLE CHITIETHDNHAP
(
    MAHD NCHAR(10) NOT NULL,
    MAMH NCHAR(10) NOT NULL,
    SOLUONG INT,
    DONGIA INT,
    CONSTRAINT PK_CHITIETHDNHAP PRIMARY KEY(MAHD, MAMH),
    CONSTRAINT FK_CHITIETHDNHAP_HOADONNHAP FOREIGN KEY (MAHD) REFERENCES HOADONNHAP(MAHD),
    CONSTRAINT FK_CHITIETHDNHAP_MATHANG FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH)
)
GO

CREATE TABLE HOADONCAHAT
(
    MAPHONG NCHAR(10),
    MANV NCHAR(10),
    MAMH NCHAR(10),
    MAKM NCHAR(10),
    MAKH NCHAR(10),
    TGBATDAU DATETIME,
    TGKETTHUC DATETIME,
    NGUOITAO NVARCHAR(50),
    NGAYTAO DATETIME,
    CONSTRAINT FK_HOADONCAHAT_PHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG),
    CONSTRAINT FK_HOADONCAHAT_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_HOADONCAHAT_MATHANG FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH),
    CONSTRAINT FK_HOADONCAHAT_KHUYENMAI FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM),
    CONSTRAINT FK_HOADONCAHAT_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)

INSERT INTO NHANVIEN (MANV, TENNV ,SDT,MAIL , DIACHI , CHUCVU , GIOITINH , TAIKHOAN ,MATKHAU)
VALUES	('NV01',N'NGUYỄN TIẾN DŨNG',N'0123123123',N'ngtiendung012@gmail.com',N' TP.HỒ CHÍ MINH ', N'SẾP',N'NAM','sepdung','12345'),
		('NV02', N'NGUYỄN TƯỜNG VI', N'0987654321', N'ntv188002@gmail.com', N'TP.HỒ CHÍ MINH', N'NHÂN VIÊN', N'NỮ', 'vi123', '12345'),
		('NV03', N'ĐẶNG XUÂN BÌNH', N'0369696969', N'xuanbinh@example.com', N'Đà Nẵng', N'QUẢN LÍ', N'NAM', 'binh123', '123'),
		('NV04', N'NGUYỄN TRƯỜNG DUY', N'0123456789', N'truongduy@example.com', N'Hà Nội', N'NHÂN VIÊN', N'NỮ', 'DUY123', '123');
--
SELECT * FROM NHANVIEN